name: Build Dev Image

on:
  push:
    tags:
      - '^([0-9]+)\.([0-9]+)\.([0-9]+)dev([0-9]+)'
      - '^([0-9]+)\.([0-9]+)dev([0-9]+)'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}  # checkout current branch
      - name: Install dependencies and validate PEP8 compliance
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: Bump version in pyproject.toml
        run: |
          poetry version ${{ github.ref_name }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build ${{ github.ref_name }} UI Dev Image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: papermerge/papermerge:${{ github.ref_name }}-ui
          file: docker/dev/Dockerfile.ui
          platforms: linux/amd64
      - name: Build ${{ github.ref_name }} Dev Image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: papermerge/papermerge:${{ github.ref_name }}
          build-args: VERSION=${{github.ref_name}}
          file: docker/dev/Dockerfile
          platforms: linux/amd64
